### ISSUE TITLE
RpcException vs. AccessTokenNotAvailableException

### ISSUE THREAD

**Issue by ChristianWeyer** [JeepNL/Blazor-WASM-Identity-gRPC#1]
Hi!

did you ever try to catch e.g. an AccessTokenNotAvailableException in your gRPC-Web calls?

Like this:
https://github.com/grpc/grpc-dotnet/issues/965

Would be interesting to see your solution.
Thanks.

**Comment by JeepNL** [comment]
I didn't try this yet but I saw James answered your question and that his suggestion works.

**Comment by ChristianWeyer** [comment]
Exactly, thanks!
