### ISSUE TITLE
Add custom login blazor component

### ISSUE THREAD

**Issue by GeorgeS2019** [JeepNL/Blazor-WASM-Identity-gRPC#5]
Most entries in Blazor Awsome use IdentityServer4 for login. 

Consider instead using blazor pages or components for login, logout  and registration

**Comment by JeepNL** [comment]
But this one is using gRPC for it. That's the difference. And here's an example without IndentityServer4 https://github.com/JeepNL/Hosted_Blazor_WASM_Identity
